# data
dataset: imagenet_randaug
randaug_N: 2
randaug_M: 10
num_workers: 6
image_size: 256
max_image_size: 256
topk: [1, 5]
batch_size: 256
test_batch_size: 1024
mixup: True
mixup_alpha: 0.2

# GPU
mp_dist: True
dist_url: 'tcp://127.0.0.1:56361'
world_size: 1
rank: 0
dist_backend: nccl

# optimizer
optimizer: sgd_no_bias_decay
momentum: 0.9
weight_decay: 0.00004
nesterov: True
label_smoothing: 0.1
#zero_gamma: True
#enable_EMA: True
#EMA_decay: 0.9999

# scheduler
lr_scheduler: cosine_decaying
#warmup_epochs: 5

# learning
lr: 0.08
slimming_sparsity_rate: 0.00001
num_epochs: 200

# model profiling
profiling: [gpu]
#profiling_only: True
#num_forwards: 1000
#pre_num_forwards: 1000
#profiling_batch_size: 64

# pruning
#update_BN: True
base_model_path: logs/sp_efficientnet/b2/imagenet/base/best_model_1.0.pt
min_size_ratio: 0.1
multi_base_pruning: True
set_pretrained_base: True
multi_base_model_path:
  - logs/sp_efficientnet/b2/imagenet/base/best_model_0.75.pt
  - logs/sp_efficientnet/b2/imagenet/base/best_model_1.0.pt
base_width_mult_list: [0.75, 1.0]
#reinit_params: True

# others
slimmable_training: True
width_mult_list: [0.5484, 0.526, 1.0]
inplace_kd: True
kd_T: 1
kd_alpha: 0.9
finetune_log_dir: logs/sp_efficientnet/b2/imagenet/finetune
best_model_path: best_model.pt
checkpoint_path: latest_checkpoint.pt
model: models.sp_efficientnet
type: b2
stochastic_depth_prob: 0.2
random_seed: 1
reset_parameters: True
init_bn_val: 1.0
#resume: True
#test_only: True
#pretrained: logs/sp_efficientnet/b2/imagenet/finetune/best_model.pt