# data
dataset: cifar10
num_workers: 6
image_size: 224
max_image_size: 256
topk: [1, 5]
batch_size: 128
test_batch_size: 1024

# GPU
mp_dist: True
dist_url: 'tcp://127.0.0.1:56361'
world_size: 1
rank: 0
dist_backend: nccl

# optimizer
optimizer: sgd
momentum: 0.9
weight_decay: 0.0001
nesterov: True

# scheduler
lr_scheduler: multistep
multistep_lr_milestones: [60, 90, 110]
multistep_lr_gamma: 0.2

# learning
lr: 0.1
slimming_sparsity_rate: 0.00001
num_epochs: 120

# model profiling
profiling: [gpu]
#profiling_only: True
#num_forwards: 1000
#pre_num_forwards: 1000
#profiling_batch_size: 64

# pruning
update_BN: True

# others
width_mult_list: [1.0]
log_dir: logs/sp_resnet50/0.5_0.75_1.0/cifar10/base
best_model_path: best_model_1.0.pt
checkpoint_path: latest_checkpoint_1.0.pt
model: models.sp_resnet
depth: 50
random_seed: 1
reset_parameters: True
init_bn_val: 0.5
#resume: True
#test_only: True
#pretrained: logs/sp_resnet50/0.5_0.75_1.0/cifar10/base/best_model_1.0.pt
